name: Nightly version update

on:
  workflow_dispatch:
  schedule:
    # Run every night at midnight UTC
    - cron: '0 0 * * *'

jobs:
  nightly-version-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update -qq
          apt-get install xmlstarlet yq -y -qq

      - name: Run the update script
        run: ./update.sh


      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet; then
            echo "changes=false" >> $GITHUB_ENV
          else
            echo "changes=true" >> $GITHUB_ENV
          fi

      - name: Build dependencies
        if: env.changes == 'true'
        run: |
          FLATHUB_REPO=https://dl.flathub.org/repo/flathub.flatpakrepo
  
          apt-get update -qq
          apt-get install -y -qq flatpak-builder flatpak build-essential git-core appstream-compose
          flatpak --user remote-add --if-not-exists flathub $FLATHUB_REPO

      - uses: actions/cache@v4
        id: flatpak-builder-cache
        if: ! env.ACT
        with:
          path: |
            .flatpak-builder
            repo
          key: flatpak-builder

      - name: Build
        if: env.changes == 'true'
        run: |
          rm -rf builddir
          flatpak-builder --force-clean --user --install-deps-from=flathub --repo=repo --install builddir com.automattic.beeper.yml

      - name: Create Pull Request for changes
        if: env.changes == 'true' && ! env.ACT
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore: bump version"
          branch: version-update
          title: "bump version"
          body: |
            This is an automated pull request to update the repository with the changes from `./update.sh`.
